// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DISC Rápido - Descubra seu Perfil Comportamental",
  description: "Avaliação DISC completa e gratuita. Descubra seu perfil comportamental em poucos minutos e receba insights personalizados para desenvolvimento pessoal e profissional.",
  keywords: "DISC, perfil comportamental, avaliação psicológica, desenvolvimento pessoal, liderança, autoconhecimento",
  authors: [{ name: "DISC Rápido" }],
  openGraph: {
    title: "DISC Rápido - Descubra seu Perfil Comportamental",
    description: "Avaliação DISC completa e gratuita. Resultados instantâneos e insights personalizados.",
    type: "website",
    locale: "pt_BR",
  },
  twitter: {
    card: "summary_large_image",
    title: "DISC Rápido - Descubra seu Perfil Comportamental",
    description: "Avaliação DISC completa e gratuita. Resultados instantâneos e insights personalizados.",
  },
  robots: {
    index: true,
    follow: true,
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}